language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9

install:
  - pip install Django==$DJANGO
  - pip install -e .

script: TEST_EXTRA=1 python setup.py test
