language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.7
  - DJANGO=1.8

install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors

script: python setup.py test
